name: "Test suite"

on:
  # Modification of a project file in the main branch
  push:
    branches:
      - main
    paths:
      # TODO: Change this to the name of your package
      - "PACKAGE_NAME/**"
      - "pyproject.toml"
      - "poetry.lock"
  # Pull request to the main branch modifying a project file
  pull_request:
    branches:
      - main
    paths:
      # TODO: Change this to the name of your package
      - "PACKAGE_NAME/**"
      - "pyproject.toml"
      - "poetry.lock"
  # Triggered by a new release
  workflow_call:

jobs:
  # TODO: Uncomment this if you don't intend to use unit testing and just want syntax checking
  #test-syntax:
  #  uses: Steffo99/.github/.github/workflows/test-poetry-compileall.yml@main

  # TODO: Uncomment this if you intend to use unit testing based on pytest
  #text-pytest:
  #  uses: Steffo99/.github/.github/workflows/test-poetry-pytest.yml@main

  # TODO: Uncomment this if you intend to use unit testing based on pytest which requires a PostgreSQL database
  #text-pytest-postgres:
  #  uses: Steffo99/.github/.github/workflows/test-poetry-pytest-postgres.yml@main
